export const DEFAULT_CATEGORIES = [
  { name: "Suscripciones", icon: "repeat", color: "#8B5CF6" },
  { name: "Compras online", icon: "shopping-bag", color: "#F59E0B" },
  { name: "Supermercado", icon: "store", color: "#10B981" },
  { name: "Restaurantes", icon: "utensils", color: "#EF4444" },
  { name: "Transporte", icon: "car", color: "#3B82F6" },
  { name: "Servicios públicos", icon: "zap", color: "#6366F1" },
  { name: "Transferencias", icon: "arrow-right-left", color: "#EC4899" },
  { name: "Salud", icon: "heart-pulse", color: "#14B8A6" },
  { name: "Entretenimiento", icon: "gamepad-2", color: "#F97316" },
  { name: "Educación", icon: "graduation-cap", color: "#06B6D4" },
  { name: "Efectivo", icon: "banknote", color: "#84CC16" },
  { name: "Retiro cajero", icon: "landmark", color: "#78716C" },
  { name: "Pago tarjeta crédito", icon: "credit-card", color: "#0EA5E9" },
  { name: "Crédito vehículo", icon: "car", color: "#7C3AED" },
  { name: "Crédito hipotecario", icon: "home", color: "#0D9488" },
  { name: "Papas", icon: "users", color: "#F472B6" },
  { name: "Cadenas", icon: "wallet", color: "#A78BFA" },
  { name: "Administración apto", icon: "home", color: "#64748B" },
  { name: "Ingresos", icon: "trending-up", color: "#22C55E" },
  { name: "Otros", icon: "package", color: "#9CA3AF" },
] as const;
